### ISSUE TITLE
Connecting to an existing warden container (possible feature request)

### ISSUE THREAD

**Issue by dhilipkumars** [cloudfoundry-attic/gordon-old#2]
Hi Team,

I know this project has not been touched since a very long time.   Is this still maintained?

I have not fully understood this project yet but from what i see it appears that this package lets us connect to warden server, create a container and execute a command in it.  Correct?

Is it possible to connect to an existing container (with appguid and instance pair) using this package? If not possible currently then could you think of any way to do that?

Thanks in Advance,
Dhilip

**Comment by dhilipkumars** [comment]
@vito

**Comment by goonzoid** [comment]
@dhilipkumars Gordon works at the Warden container level, rather than the app-instance level, so isn't aware of appguids, etc.

If you want to get inside a running CF app, there's some info here: http://andypiper.co.uk/2014/02/17/getting-inside-cloud-foundry-for-debug-and-profit - look for the section entitled "WARDEN CONTAINERS AND SHELLS". Hope that helps!

**Comment by dhilipkumars** [comment]
@goonzoid Thanks for the response and Apologies for the delay in responding.
